name: CI_STORE_DEPLOY_ANDROID

on:
  # Run this workflow when any new code is pushed into the main branch
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: pod --version

      - run: xcodebuild -version
